version: '3.1'

services:
  mongodb:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    restart: always
    env_file:
    - .env
    ports:
    - 27017:27017
    volumes:
    - mongodb-data:/data
    - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default

  redis:
    image: redis:7.2.5-alpine
    ports:
    - 63791:63791
    volumes:
    - redis_data:/data
    env_file:
    - .env

  rabbitmq:
    image: rabbitmq:3.13-alpine
    env_file:
    - .env
    ports:
      - 5674:5674
      - 15695:15695
    volumes:
    - rabbitmq:/var/lib/rabbitmq

  ratings_web:
    build: ./
    ports:
    - 3002:3002
    depends_on:
    - mongodb

    env_file:
    - .env
    container_name: ratings_web

  sneakers:
    build: .
    depends_on:
    - mongodb
    - rabbitmq
    volumes:
    - ./docker/sneakers.sh:/docker-entrypoint-initdb.d/sneakers.sh:ro


volumes:
  mongodb-data:
  postgres-data:
  redis_data:
  rabbitmq:
