version: '3.1'

services:
  mongodb:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    restart: always
    env_file:
    - .env
    ports:
    - 27017:27017
    volumes:
    - mongodb-data:/data
    - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default

  nginx:
    image: nginx:1.14.2-alpine
    ports:
      - '8008:591'
    volumes:
      - ./nginx.conf.d:/etc/nginx/nginx.conf
    networks:
      - nginx_network_1

  ratings_web:
    build: ./
    ports:
    - 3002:3002
    depends_on:
    - mongodb

    env_file:
    - .env
    container_name: ratings_web
    networks:
    - nginx_network_1


  redis:
    image: redis:6.2.13
    ports:
    - 63791:63791
    volumes:
    - redis_data:/data
    env_file:
    - .env

  rabbitmq:
    image: rabbitmq:3.9.29-alpine
    env_file:
    - .env
    ports:
      - 5674:5674
      - 15695:15695
    volumes:
    - rabbitmq:/var/lib/rabbitmq

volumes:
  mongodb-data:
  postgres-data:
  redis_data:
  rabbitmq:


networks:
  nginx_network_1:
    external: true
