development:
  clients:
    default:
      uri: "mongodb://mongouser:mongopwd@localhost:27017/mg-process-ratings"
      server_selection_timeout: 2
      connect_timeout: 5
      socket_timeout: 5
      min_pool_size: 1
      max_pool_size: 10
  options:

test:
  clients:
    default:
      uri: "mongodb://test:test@localhost:27017/mg-test"
      max_pool_size: 1
  options:
